name: Run Pytest on push

on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:

jobs:
  dev_deployment:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5
      name: Setup Python
      with:
        python-version: '3.10'
    
    - uses: actions/setup-java@v4
      name: Setup Java
      with:
        java-version: '21'
        distribution: temurin
    
    - uses: vemonet/setup-spark@v1
      name: Setup Spark
      with:
        spark-version: '3.4.1'
        hadoop-version: '3'
        
    - name: Run Pytest
      run: echo "Testinh"
      
    
    - run: spark-submit --version
