name: Run Pytest on push

on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:

jobs:
  dev_deployment:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Spark
      id: cache-spark
      uses: actions/cache@v4
      with:
        path: /home/runner/work/Unit-Testing/spark-3.4.1-bin-hadoop3
        key: ${{ runner.os }}-spark

    - uses: actions/setup-python@v5
      name: Setup Python
      with:
        python-version: '3.10'
    
    - uses: actions/setup-java@v4
      name: Setup Java
      with:
        java-version: '21'
        distribution: temurin
    
    - name: Setup Spark
      uses: vemonet/setup-spark@v1
      if: steps.cache-spark.outputs.cache-hit != 'true'
      with:
        spark-version: '3.4.1'
        hadoop-version: '3'
    
    - name: Install Requirements
      run: pip install -r requirements.txt
        
    - name: Run Pytest
      run: spark-submit --version
      
